# WhatATheme and thanks to rohandas28 for theme style
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 
# Title of the Site
title: Hackfluentz
# Description of the Site
description: Web Penetration Tester And Self Learner
# URL of Image of the Site
site-image: /assets/images/post.jpg
# Keywords of the Site
site-keywords: hackfluentz, hack fluentz, hack, fluentz, hackfluentz tech, hackfluentz githun, coder
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/hero.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hackfluentzofficial@gmail.com
facebook_username: 
twitter_username: hackfluentz
instagram_username: hacking.science
linkedin_username: hackfluentz
github_username:  hackfluentz
youtube_channel_id: UC59EEFqddkLityl-4jEjAOw
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
telegram_username: hackfluentz

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: hackfluentz

# Name of the Author
author-name: Hackfluentz
# URL for the Image of the Author
author-image: https://hackfluentz.github.io/assets/images/Brand.png
# 60 Words About the Author
author-about: Hackfluentz is a web penetaration tester, who has a good command in sql injection, learning bughunting and python. Also, he is a logo designer and loves to devlop tech gadgets, who has a YouTube channel named hackfluentz tech where he teach hacking in short videos. For more information, you can contact me via mail and social media.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/hackfluentz

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
